name: Price Drop Tracker

on:
  push:
    branches: [ "master", "main" ]
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch: # এই লাইনটিই 'Run workflow' বাটনটি আনে

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-dotenv

      - name: Run tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tracker.py